import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${rubik.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <a
          href="https://matrn.dev"
          target="_blank"
          rel="noreferrer"
          className="fixed bottom-4 right-4 rounded-full bg-slate-900 border border-slate-800 px-3 py-1.5 text-xs transition-opacity hover:opacity-80"
        >
          matrn.dev
        </a>
      </body>
      
    </html>
  );
}
